const timezones = [
    { abbr: "PST", name: "Pacific Standard Time (UTC-8)", iana: "America/Los_Angeles" },
    { abbr: "PDT", name: "Pacific Daylight Time (UTC-7)", iana: "America/Los_Angeles" },
    { abbr: "MST", name: "Mountain Standard Time (UTC-7)", iana: "America/Denver" },
    { abbr: "MDT", name: "Mountain Daylight Time (UTC-6)", iana: "America/Denver" },
    { abbr: "CST", name: "Central Standard Time (UTC-6)", iana: "America/Chicago" },
    { abbr: "CDT", name: "Central Daylight Time (UTC-5)", iana: "America/Chicago" },
    { abbr: "EST", name: "Eastern Standard Time (UTC-5)", iana: "America/New_York" },
    { abbr: "EDT", name: "Eastern Daylight Time (UTC-4)", iana: "America/New_York" },
    { abbr: "AST", name: "Atlantic Standard Time (UTC-4)", iana: "America/Halifax" },
    { abbr: "ADT", name: "Atlantic Daylight Time (UTC-3)", iana: "America/Halifax" },
    { abbr: "NST", name: "Newfoundland Standard Time (UTC-3:30)", iana: "America/St_Johns" },
    { abbr: "NDT", name: "Newfoundland Daylight Time (UTC-2:30)", iana: "America/St_Johns" },
    { abbr: "AKST", name: "Alaska Standard Time (UTC-9)", iana: "America/Anchorage" },
    { abbr: "AKDT", name: "Alaska Daylight Time (UTC-8)", iana: "America/Anchorage" },
    { abbr: "HST", name: "Hawaii-Aleutian Standard Time (UTC-10)", iana: "Pacific/Honolulu" },
    { abbr: "HDT", name: "Hawaii-Aleutian Daylight Time (UTC-9)", iana: "Pacific/Honolulu" },
    { abbr: "GMT", name: "Greenwich Mean Time (UTC±00:00)", iana: "Etc/GMT" },
    { abbr: "WET", name: "Western European Time (UTC+0)", iana: "Europe/London" },
    { abbr: "CET", name: "Central European Time (UTC+1)", iana: "Europe/Paris" },
    { abbr: "WAT", name: "West African Time (UTC+1)", iana: "Africa/Lagos" },
    { abbr: "EET", name: "Eastern European Time (UTC+2)", iana: "Europe/Kiev" },
    { abbr: "MSK", name: "Moscow Standard Time (UTC+3)", iana: "Europe/Moscow" },
    { abbr: "GST", name: "Gulf Standard Time (UTC+4)", iana: "Asia/Dubai" },
    { abbr: "PKT", name: "Pakistan Standard Time (UTC+5)", iana: "Asia/Karachi" },
    { abbr: "IST", name: "Indian Standard Time (UTC+5:30)", iana: "Asia/Kolkata" },
    { abbr: "WIB", name: "Western Indonesia Time (UTC+7)", iana: "Asia/Jakarta" },
    { abbr: "ICT", name: "Indochina Time (UTC+7)", iana: "Asia/Bangkok" },
    { abbr: "CST", name: "China Standard Time (UTC+8)", iana: "Asia/Shanghai" },
    { abbr: "HKT", name: "Hong Kong Time (UTC+8)", iana: "Asia/Hong_Kong" },
    { abbr: "JST", name: "Japan Standard Time (UTC+9)", iana: "Asia/Tokyo" },
    { abbr: "KST", name: "Korea Standard Time (UTC+9)", iana: "Asia/Seoul" },
    { abbr: "WIT", name: "Eastern Indonesia Time (UTC+9)", iana: "Asia/Jayapura" },
    { abbr: "CST", name: "Central Standard Time (UTC+8:30)", iana: "Australia/Eucla" },
    { abbr: "ACST", name: "Australian Central Standard Time (UTC+9:30)", iana: "Australia/Darwin" },
    { abbr: "AEST", name: "Australian Eastern Standard Time (UTC+10)", iana: "Australia/Sydney" },
    { abbr: "AEDT", name: "Australian Eastern Daylight Time (UTC+11)", iana: "Australia/Sydney" },
    { abbr: "ChST", name: "Chamorro Standard Time (UTC+10)", iana: "Pacific/Guam" },
    { abbr: "CAT", name: "Central African Time (UTC+2)", iana: "Africa/Johannesburg" },
    { abbr: "EAT", name: "East African Time (UTC+3)", iana: "Africa/Nairobi" },
    { abbr: "AST", name: "Arabic Standard Time (UTC+3)", iana: "Africa/Khartoum" },
    { abbr: "WAST", name: "West Africa Summer Time (UTC+2)", iana: "Africa/Windhoek" },
    { abbr: "EAST", name: "East Africa Summer Time (UTC+3)", iana: "Indian/Comoro" },
    { abbr: "SAST", name: "South Africa Standard Time (UTC+2)", iana: "Africa/Johannesburg" },
    { abbr: "RET", name: "Reunion Time (UTC+4)", iana: "Indian/Reunion" },
    { abbr: "MUT", name: "Mauritius Time (UTC+4)", iana: "Indian/Mauritius" },
    { abbr: "SCT", name: "Seychelles Time (UTC+4)", iana: "Indian/Mahe" },
    { abbr: "EUST", name: "Eastern European Summer Time (UTC+2)", iana: "Africa/Tripoli" },
    { abbr: "CET", name: "Central European Time (UTC+1)", iana: "Africa/Ceuta" },
    { abbr: "WET", name: "Western European Time (UTC+0)", iana: "Africa/El_Aaiun" },
    { abbr: "GMT", name: "Greenwich Mean Time (UTC±00:00)", iana: "Africa/Ouagadougou" },


];

export default timezones;
