const timezones = [
    { abbr: "PST", name: "Pacific Standard Time (UTC-8)" },
    { abbr: "PDT", name: "Pacific Daylight Time (UTC-7)" },
    { abbr: "MST", name: "Mountain Standard Time (UTC-7)" },
    { abbr: "MDT", name: "Mountain Daylight Time (UTC-6)" },
    { abbr: "CST", name: "Central Standard Time (UTC-6)" },
    { abbr: "CDT", name: "Central Daylight Time (UTC-5)" },
    { abbr: "EST", name: "Eastern Standard Time (UTC-5)" },
    { abbr: "EDT", name: "Eastern Daylight Time (UTC-4)" },
    { abbr: "AST", name: "Atlantic Standard Time (UTC-4)" },
    { abbr: "ADT", name: "Atlantic Daylight Time (UTC-3)" },
    { abbr: "NST", name: "Newfoundland Standard Time (UTC-3:30)" },
    { abbr: "NDT", name: "Newfoundland Daylight Time (UTC-2:30)" },
    { abbr: "AKST", name: "Alaska Standard Time (UTC-9)" },
    { abbr: "AKDT", name: "Alaska Daylight Time (UTC-8)" },
    { abbr: "HST", name: "Hawaii-Aleutian Standard Time (UTC-10)" },
    { abbr: "HDT", name: "Hawaii-Aleutian Daylight Time (UTC-9)" },
    { abbr: "GMT", name: "Greenwich Mean Time (UTC±00:00)" },
    { abbr: "WET", name: "Western European Time (UTC+0)" },
    { abbr: "CET", name: "Central European Time (UTC+1)" },
    { abbr: "EET", name: "Eastern European Time (UTC+2)" },
    { abbr: "MSK", name: "Moscow Standard Time (UTC+3)" },
    { abbr: "GST", name: "Gulf Standard Time (UTC+4)" },
    { abbr: "PKT", name: "Pakistan Standard Time (UTC+5)" },
    { abbr: "IST", name: "Indian Standard Time (UTC+5:30)" },
    { abbr: "BST", name: "Bangladesh Standard Time (UTC+6)" },
    { abbr: "ICT", name: "Indochina Time (UTC+7)" },
    { abbr: "CST", name: "China Standard Time (UTC+8)" },
    { abbr: "JST", name: "Japan Standard Time (UTC+9)" },
    { abbr: "AEST", name: "Australian Eastern Standard Time (UTC+10)" },
    { abbr: "AEDT", name: "Australian Eastern Daylight Time (UTC+11)" },
    { abbr: "NZST", name: "New Zealand Standard Time (UTC+12)" },
    { abbr: "NZDT", name: "New Zealand Daylight Time (UTC+13)" },
];

export default timezones;
